### ISSUE TITLE
Adding a README file

### ISSUE THREAD

**Issue by loneWarrior581** [sarthakkundra/polling-app#1]
The current application has no `README` file for understanding the idea behind the project.So adding a `README` would enhance the chance of the more engagment among contributors.

**Comment by sarthakkundra** [comment]
Thanks a lot for taking up this issue! i couldn't find time to get around to it. Please refer to this [article]https://dev.to/scottydocs/how-to-write-a-kickass-readme-5af9l) for the format. If you need help regarding any step feel free to comment down :)

**Comment by loneWarrior581** [comment]
@sarthakkundra the above link is not working and could you please make a layout for idea of the project.

**Comment by sarthakkundra** [comment]
@loneWarrior581 I will add the basic parts of how to get a local copy up and running and will let you know so that you can complete the rest of it

**Comment by sarthakkundra** [comment]
@loneWarrior581 I have added the basic instructions to set up a local copy.  Please format the readme properly :-

1. Add links to the tech stack part to the official documentation of all the frameworks/libraries.
2. Add the scripts in getting started part in single line code snippets " `` " denoted by these (back ticks) 
3. Add a contributing sub heading and proper steps inside of it.
4. Add a project mentors section at the bottom.
5. Add badges on top (optional)

Please acknowledge within the next 24 hours if you're working on this or not.

**Comment by loneWarrior581** [comment]
Yes @sarthakkundra sir I will start working on this today only. Is the demo version of this application deployed?

**Comment by sarthakkundra** [comment]
@loneWarrior581 no, because if you'll setup the application on your system you'll notice that the app is almost complete but the UI is bare bones HTML. So it'll be deployed after we have a presentable UI

**Comment by sarthakkundra** [comment]
@loneWarrior581  Updates?

**Comment by loneWarrior581** [comment]
@sarthakkundra sir bought a new laptop today and was busy setting it up , working on it will get to you soon and sorry for the delay caused.

**Comment by loneWarrior581** [comment]
@sarthakkundra sir shall I add the way to set up the **remote mongoDb** i.e **mongodb atlas** because mongodb is **not compatable** for **32 bit** OS. This would be helpful for those who have 32 bit OS.

This would just require a **.env**  file for the datafield/credentials containing the `password` , `username` and the `URI` for the remote **mongoDb-atlas** **[(link)](https://www.mongodb.com/cloud/atlas)**   and **.env.sample** in for the format for the people setting up the project in the local system. 

PS : Sir please do acknowledge this.

**Comment by sarthakkundra** [comment]
@loneWarrior581 I don't think that is required as we'll be shifting to a dev mongoDB atlas DB for ease of use for everyone and then we'll just need to create one MONGO_URI in the .env file instead of 2-3 variables.
