### ISSUE TITLE
Tests for authentication routes

### ISSUE THREAD

**Issue by sarthakkundra** [sarthakkundra/polling-app#8]
Write tests for the back-end routes for authenticating a user. There are two routes so there needs to be tests for passing as well as failing the routes.

- [ ] Creating a user.

- [ ] Loggin in a user.

Attach a screenshot of the tests passing with the PR.

**Comment by dumbbellcode** [comment]
Testing scripts will be in which language ?. Can you provide some resources ? 
I have been testing my APIs from postman so far.

**Comment by heet-2312** [comment]
may i work on this?

**Comment by sarthakkundra** [comment]
@Sudheer121 This project is under an even called SLoP so for now I can only assign issues to the registered participants. Sorry.

**Comment by sarthakkundra** [comment]
@heet-2312 Yes, you can. Setup the tests using Jest. You have 72 hours to work on this and provide an update.

**Comment by jespicas** [comment]
https://github.com/sarthakkundra/polling-app/pull/10

**Comment by jespicas** [comment]
According Hacktoberfest web, this project not participate because is missing a topic "hacktoberfets" 
![nofound](https://user-images.githubusercontent.com/3797505/95045427-51390900-06e2-11eb-94d7-14abe0b0c51e.png)

**Comment by heet-2312** [comment]
@sarthakkundra  I see a pull request has already been been made to my task assigned so should i still work on it?

**Comment by sarthakkundra** [comment]
@heet-2312 Yes, you have been assigned the issue so you can still work on it. If you can make a PR before the allotted time period I'll merge that otherwise this.

**Comment by sarthakkundra** [comment]
@jespicas I think this has happened after the newly incorporated changes in Hacktoberfest guidelines due to spam PRs

**Comment by heet-2312** [comment]
i am making a PR although there are not many changes the person had created just in the standard way which i had learned you can merge if it is correct

**Comment by jespicas** [comment]
> @jespicas I think this has happened after the newly incorporated changes in Hacktoberfest guidelines due to spam PRs

I think if you want to participate in Hacktoberfest, you should add tag hacktoberfest in the repo ? 
![Screenshot_1](https://user-images.githubusercontent.com/3797505/95174085-d9d6a880-07b9-11eb-8790-b506f1cc9073.png)
